### ISSUE TITLE
non-JS module files deprecated.

### ISSUE THREAD

**Issue by Meeeds** [backendclub/example-django-devcontainers#1]
Hello,

Everything works on my computer, but when I open the URL from chrome, I correct see the html returned by the server in chome console, but Chrome  shows ERR_ADDRESS_INVALID and in the console there is this error :

```
crbug/1173575, non-JS module files deprecated.
(anonymous) @ VM628:5
```

**Comment by yoongkang** [comment]
Don't think I've ever seen that one. Have you tried running Django on another port? 

I might need to update some of the configuration due to port conflicts.

**Comment by yoongkang** [comment]
Also these instructions from my [blog post](https://backendclub.com/articles/django-dev-environment-vscode-remote-containers/#adding-postgres) might help:

> Sometimes I’ve found that VSCode would fail to forward the port automatically now that we’ve published port 8000 in the docker-compose.yml, which conflicts with the port forwarding feature. In that case you should try runserver by binding to 0.0.0.0, i.e. python manage.py runserver 0.0.0.0:8000.
> 
> Alternatively, you could also just remove ports from the docker-compose.yml file. Or if you don’t want to do that, you can use an independent docker-compose.yml file in the .devcontainer folder that does not publish ports. You will need to modify devcontainer.json to use only one Docker Compose configuration file.

**Comment by yoongkang** [comment]
Closing as not likely to be an issue with the code.
